export const ErrorTypes = {
  //META MASK ERROR
  META_MASK_NOT_INSTALL: "META_MASK_NOT_INSTALL",
  META_MASK_CONNECTION_REJECTED: "META_MASK_CONNECTION_REJECTED",
  META_MASK_USER_DENIED_TRANSACTION: "META_MASK_USER_DENIED_TRANSACTION",
  CONNECT_YOUR_ACCOUNT: "CONNECT_YOUR_ACCOUNT",
  WRONG_CHAIN_ID: "WRONG_CHAIN_ID",
  ADD_PRODUCT: "ADD_PRODUCT",
  PRODUCT_NOT_EXIST: "PRODUCT_NOT_EXIST",
};
